
body_x = 100
body_y = 150
bottom_z = 15
bottom_wall_thikness = 1.5

dist_between_whells = body_y / 2
wheel_window = 40 